mvccrud/Controllers/CalisanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using mvccrud.Models;

namespace mvccrud.Controllers
{
    public class CalisanController : Controller
    {
        // GET: Calisan
        public ActionResult Index()
        {
            IEnumerable<mvccalisanmodel> callist;
            HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Calisanlars").Result;
            callist = response.Content.ReadAsAsync<IEnumerable<mvccalisanmodel>>().Result;
            return View(callist);
        }
        public ActionResult EY(int id = 0)//sayfaya veri gelir id 
        {
            if (id == 0)
            {
                return View(new mvccalisanmodel());
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Calisanlars/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvccalisanmodel>().Result);
            }
        }

        [HttpPost]
        public ActionResult EY(mvccalisanmodel calisan)
        {
            if (calisan.CalisanID == 0)
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.PostAsJsonAsync("Calisanlars", calisan).Result;
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.PutAsJsonAsync("Calisanlars/" + calisan.CalisanID, calisan).Result;
                return View(response.Content.ReadAsAsync<mvccalisanmodel>().Result);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {

            HttpResponseMessage response = GlobalVariables.webapiclient.DeleteAsync("Calisanlars/" + id.ToString()).Result;
            return RedirectToAction("Index");

        }
    }
}

mvccrud/Controllers/FirmaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using mvccrud.Models;

namespace mvccrud.Controllers
{
    public class FirmalarController : Controller
    {
        // GET: Firmalar
        public ActionResult Index()
        {
            IEnumerable<mvcfirmamodel> callist;
            HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Firmalars").Result;
            callist = response.Content.ReadAsAsync<IEnumerable<mvcfirmamodel>>().Result;
            return View(callist);
        }
        public ActionResult EY(int id = 0)//sayfaya veri gelir id 
        {
            if (id == 0)
            {
                return View(new mvcfirmamodel());
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Firmalars/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcfirmamodel>().Result);
            }
        }
        [HttpPost]
        public ActionResult EY(mvcfirmamodel firma)
        {
            if (firma.FirmaNo == 0)
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.PostAsJsonAsync("Firmalars", firma).Result;
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.PutAsJsonAsync("Firmalars/" + firma.FirmaNo, firma).Result;
                
            }
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            HttpResponseMessage response = GlobalVariables.webapiclient.DeleteAsync("Firmalars/" + id.ToString()).Result;
            return RedirectToAction("Index");

        }
    }
}

mvccrud/Controllers/SubelerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using mvccrud.Models;

namespace mvccrud.Controllers
{
    public class SubelerController : Controller
    {
        // GET: Subeler
        public ActionResult Index()
        {
            IEnumerable<mvcsubemodel> callist;
            HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Subelers").Result;
            callist = response.Content.ReadAsAsync<IEnumerable<mvcsubemodel>>().Result;
            return View(callist);
        }

        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View(new mvcsubemodel());
            }
            else
            {
                //Api/Urunlers/1
                HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Subelers/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcsubemodel>().Result);
            }
        }
        [HttpPost]
        public ActionResult EY(mvcsubemodel sube)
        {
            if (sube.SubeNo == 0)
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.PostAsJsonAsync("Subelers", sube).Result;
            }
            else
            {
                //Api/Urunlers/1
                HttpResponseMessage response = GlobalVariables.webapiclient.PutAsJsonAsync("Subelers/" + sube.SubeNo, sube).Result;

            }
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        { 
            HttpResponseMessage response = GlobalVariables.webapiclient.DeleteAsync("Subelers/" + id.ToString()).Result;
            return RedirectToAction("Index");
        }
    }
}

mvccrud/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using mvccrud.Models;

namespace mvccrud.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        public ActionResult Index()
        {
            IEnumerable<mvcurunmodel> callist;
            HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Urunlers").Result;
            callist = response.Content.ReadAsAsync<IEnumerable<mvcurunmodel>>().Result;
            return View(callist);
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View(new mvcurunmodel());
            }
            else
            {
                //Api/Urunlers/1
                HttpResponseMessage response = GlobalVariables.webapiclient.DeleteAsync("Urunlers/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcurunmodel>().Result);
            }
        }

        [HttpPost]
        public ActionResult EY(mvcurunmodel urun)
        {
            if (urun.UrunNo == 0)
            {
                HttpResponseMessage response = GlobalVariables.webapiclient.PostAsJsonAsync("Urunlers", urun).Result;
            }
            else
            {
                //Api/Urunlers/1
                HttpResponseMessage response = GlobalVariables.webapiclient.PutAsJsonAsync("Urunlers/" + urun.UrunNo, urun).Result;
            
            }  
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            HttpResponseMessage response = GlobalVariables.webapiclient.GetAsync("Urunlers/" + id.ToString()).Result;
            return RedirectToAction("Index");
        }


    }
}

mvccrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Calisanlar Bilgisi ", "Index", "Calisan")</li>
                    <li>@Html.ActionLink("Sube Bilgisi", "Index", "Subeler")</li>
                    <li>@Html.ActionLink("Urun Bilgisi", "Index", "Urun")</li>
                    <li>@Html.ActionLink("Firma Bilgisi", "Index", "Firmalar")</li>
                    <li>@Html.ActionLink("Imalat Bilgisi", "Index", "Imalatlar")</li>
                    <li>@Html.ActionLink("Satilan Bilgisi", "Index", "Satilanlar")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>